services:
  adversarial:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./src:/workspace/src
    shm_size: "8gb"
    command: python /workspace/src/adversarial.py
